/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Xu0RJJ6zN8Y
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Caudex } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

caudex({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
* */
import Link from 'next/link';

import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Sheet, SheetContent, SheetTrigger } from '@/components/ui/sheet';
import { Textarea } from '@/components/ui/textarea';

export default function AboutMe() {
  return (
    <div className="flex min-h-screen flex-col">
      <header className="flex items-center justify-between bg-gray-900 px-6 py-4 text-white md:px-12">
        <Link className="text-2xl font-bold" href="#">
          John Doe
        </Link>
        <nav className="hidden items-center space-x-6 md:flex">
          <Link className="hover:text-gray-400" href="#">
            About
          </Link>
          <Link className="hover:text-gray-400" href="#">
            Projects
          </Link>
          <Link className="hover:text-gray-400" href="#">
            Skills
          </Link>
          <Link className="hover:text-gray-400" href="#">
            Contact
          </Link>
        </nav>
        <Button className="md:hidden" size="icon" variant="ghost">
          <MenuIcon className="size-6" />
          <span className="sr-only">Toggle navigation</span>
        </Button>
      </header>
      <Sheet>
        <SheetTrigger asChild>
          <Button
            className="fixed right-4 top-4 z-50 md:hidden"
            size="icon"
            variant="ghost"
          >
            <MenuIcon className="size-6" />
            <span className="sr-only">Toggle navigation</span>
          </Button>
        </SheetTrigger>
        <SheetContent
          className="w-full bg-gray-900 p-6 text-white md:w-80"
          side="right"
        >
          <div className="flex flex-col space-y-4">
            <Link className="hover:text-gray-400" href="#">
              About
            </Link>
            <Link className="hover:text-gray-400" href="#">
              Projects
            </Link>
            <Link className="hover:text-gray-400" href="#">
              Skills
            </Link>
            <Link className="hover:text-gray-400" href="#">
              Contact
            </Link>
          </div>
        </SheetContent>
      </Sheet>
      <main className="flex-1">
        <section className="bg-gray-100 py-12 md:py-20" id="about">
          <div className="container mx-auto px-6 md:px-12">
            <div className="grid grid-cols-1 items-center gap-8 md:grid-cols-2">
              <div>
                <img
                  alt="John Doe"
                  className="rounded-lg"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: '400/400',
                    objectFit: 'cover',
                  }}
                  width={400}
                />
              </div>
              <div>
                <h2 className="mb-4 text-3xl font-bold">About Me</h2>
                <p className="mb-6 text-gray-600">
                  Hi, I'm John Doe, a passionate web developer with a strong
                  background in front-end technologies. I love creating
                  beautiful and functional websites that provide a great user
                  experience.
                </p>
                <Button>Download Resume</Button>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-white py-12 md:py-20" id="projects">
          <div className="container mx-auto px-6 md:px-12">
            <h2 className="mb-8 text-3xl font-bold">My Projects</h2>
            <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
              <Card>
                <CardContent className="p-6">
                  <img
                    alt="Project 1"
                    className="mb-4 rounded-lg"
                    height={225}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: '400/225',
                      objectFit: 'cover',
                    }}
                    width={400}
                  />
                  <h3 className="mb-2 text-xl font-bold">Project 1</h3>
                  <p className="mb-4 text-gray-600">
                    A brief description of the first project.
                  </p>
                  <div className="flex justify-end">
                    <Link
                      className="text-blue-500 hover:text-blue-700"
                      href="#"
                    >
                      View Project
                    </Link>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-6">
                  <img
                    alt="Project 2"
                    className="mb-4 rounded-lg"
                    height={225}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: '400/225',
                      objectFit: 'cover',
                    }}
                    width={400}
                  />
                  <h3 className="mb-2 text-xl font-bold">Project 2</h3>
                  <p className="mb-4 text-gray-600">
                    A brief description of the second project.
                  </p>
                  <div className="flex justify-end">
                    <Link
                      className="text-blue-500 hover:text-blue-700"
                      href="#"
                    >
                      View Project
                    </Link>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-6">
                  <img
                    alt="Project 3"
                    className="mb-4 rounded-lg"
                    height={225}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: '400/225',
                      objectFit: 'cover',
                    }}
                    width={400}
                  />
                  <h3 className="mb-2 text-xl font-bold">Project 3</h3>
                  <p className="mb-4 text-gray-600">
                    A brief description of the third project.
                  </p>
                  <div className="flex justify-end">
                    <Link
                      className="text-blue-500 hover:text-blue-700"
                      href="#"
                    >
                      View Project
                    </Link>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="bg-gray-100 py-12 md:py-20" id="skills">
          <div className="container mx-auto px-6 md:px-12">
            <h2 className="mb-8 text-3xl font-bold">My Skills</h2>
            <div className="grid grid-cols-2 gap-8 md:grid-cols-4">
              <div className="rounded-lg bg-white p-6 shadow-md">
                <HashIcon className="mb-4 size-12" />
                <h3 className="mb-2 text-xl font-bold">HTML</h3>
                <p className="text-gray-600">
                  Proficient in writing semantic and accessible HTML.
                </p>
              </div>
              <div className="rounded-lg bg-white p-6 shadow-md">
                <CodepenIcon className="mb-4 size-12" />
                <h3 className="mb-2 text-xl font-bold">CSS</h3>
                <p className="text-gray-600">
                  Skilled in creating responsive and visually appealing designs.
                </p>
              </div>
              <div className="rounded-lg bg-white p-6 shadow-md">
                <CodepenIcon className="mb-4 size-12" />
                <h3 className="mb-2 text-xl font-bold">JavaScript</h3>
                <p className="text-gray-600">
                  Proficient in writing clean and efficient JavaScript code.
                </p>
              </div>
              <div className="rounded-lg bg-white p-6 shadow-md">
                <CodepenIcon className="mb-4 size-12" />
                <h3 className="mb-2 text-xl font-bold">React</h3>
                <p className="text-gray-600">
                  Experienced in building modern and scalable React
                  applications.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-white py-12 md:py-20" id="contact">
          <div className="container mx-auto px-6 md:px-12">
            <h2 className="mb-8 text-3xl font-bold">Get in Touch</h2>
            <form className="mx-auto max-w-md">
              <div className="mb-4">
                <Label htmlFor="name">Name</Label>
                <Input id="name" placeholder="Enter your name" type="text" />
              </div>
              <div className="mb-4">
                <Label htmlFor="email">Email</Label>
                <Input id="email" placeholder="Enter your email" type="email" />
              </div>
              <div className="mb-4">
                <Label htmlFor="message">Message</Label>
                <Textarea id="message" placeholder="Enter your message" />
              </div>
              <Button className="w-full" type="submit">
                Send Message
              </Button>
            </form>
          </div>
        </section>
      </main>
      <footer className="bg-gray-900 p-6 text-white md:px-12">
        <div className="container mx-auto flex items-center justify-between">
          <p>© 2024 John Doe. All rights reserved.</p>
          <div className="flex space-x-4">
            <Link className="hover:text-gray-400" href="#">
              <GithubIcon className="size-6" />
            </Link>
            <Link className="hover:text-gray-400" href="#">
              <LinkedinIcon className="size-6" />
            </Link>
            <Link className="hover:text-gray-400" href="#">
              <TwitterIcon className="size-6" />
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

function CodepenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5 12 2" />
      <line x1="12" x2="12" y1="22" y2="15.5" />
      <polyline points="22 8.5 12 15.5 2 8.5" />
      <polyline points="2 15.5 12 8.5 22 15.5" />
      <line x1="12" x2="12" y1="2" y2="8.5" />
    </svg>
  );
}

function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  );
}

function HashIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="9" y2="9" />
      <line x1="4" x2="20" y1="15" y2="15" />
      <line x1="10" x2="8" y1="3" y2="21" />
      <line x1="16" x2="14" y1="3" y2="21" />
    </svg>
  );
}

function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  );
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  );
}
