/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8KpXvDX8vD7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Landing() {
  return (
    <div className="w-full bg-gradient-to-r from-[#f1f5f9] to-[#e2e8f0] dark:from-[#1e293b] dark:to-[#0f172a] py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="grid items-center gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                Image Upscaler
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Enhance Your Images with Precision</h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Our advanced image upscaler uses cutting-edge AI technology to transform your low-quality images into
                high-resolution masterpieces, without compromising quality.
              </p>
            </div>
            <ul className="grid gap-4">
              <li className="flex items-center gap-2">
                <div className="bg-gradient-to-r from-[#6366f1] to-[#8b5cf6] rounded-md p-2 text-white">
                  <ZoomInIcon className="h-5 w-5" />
                </div>
                <div>
                  <h3 className="text-lg font-medium">Upscale with Precision</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Our algorithm intelligently enhances image details without introducing artifacts or distortions.
                  </p>
                </div>
              </li>
              <li className="flex items-center gap-2">
                <div className="bg-gradient-to-r from-[#10b981] to-[#34d399] rounded-md p-2 text-white">
                  <MaximizeIcon className="h-5 w-5" />
                </div>
                <div>
                  <h3 className="text-lg font-medium">Maintain Image Quality</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Our upscaler preserves the original image's sharpness, colors, and details, ensuring a seamless
                    transformation.
                  </p>
                </div>
              </li>
              <li className="flex items-center gap-2">
                <div className="bg-gradient-to-r from-[#f59e0b] to-[#fbbf24] rounded-md p-2 text-white">
                  <LayersIcon className="h-5 w-5" />
                </div>
                <div>
                  <h3 className="text-lg font-medium">Batch Processing</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Upscale multiple images at once, saving you time and effort.
                  </p>
                </div>
              </li>
            </ul>
          </div>
          <img
            alt="Image Upscaler"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
            height="310"
            src="/placeholder.svg"
            width="550"
          />
        </div>
      </div>
    </div>
  )
}

function LayersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z" />
      <path d="m22 17.65-9.17 4.16a2 2 0 0 1-1.66 0L2 17.65" />
      <path d="m22 12.65-9.17 4.16a2 2 0 0 1-1.66 0L2 12.65" />
    </svg>
  )
}


function MaximizeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 3H5a2 2 0 0 0-2 2v3" />
      <path d="M21 8V5a2 2 0 0 0-2-2h-3" />
      <path d="M3 16v3a2 2 0 0 0 2 2h3" />
      <path d="M16 21h3a2 2 0 0 0 2-2v-3" />
    </svg>
  )
}


function ZoomInIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <line x1="21" x2="16.65" y1="21" y2="16.65" />
      <line x1="11" x2="11" y1="8" y2="14" />
      <line x1="8" x2="14" y1="11" y2="11" />
    </svg>
  )
}
